### ISSUE TITLE
Are you gonna publish usermode ?

### ISSUE THREAD

**Issue by SSecrett** [akitaxd/filedriver#1]

**Comment by akitaxd** [comment]
idk im too lazy also its not that hard

**Comment by SSecrett** [comment]
you did make driver and didnt make usermode huh i want to see usermode bcs i need to understand for Clear base like this driver to write mine from 0

**Comment by akitaxd** [comment]
too lazy to upload* but k ill upload it when im home

**Comment by SSecrett** [comment]
When...

**Comment by akitaxd** [comment]
dn
