### ISSUE TITLE
i mapped your driver

### ISSUE THREAD

**Issue by SSecrett** [akitaxd/filedriver#2]
i mapped your driver with my mapper well but .inf not usable to create bcs still it detected as 3rd party 
how do you load your driver and run it 

after me run with CMD prompt  gives 647 error code
( faced with DSE stuff and more fixed them but stucked at running )

**Comment by akitaxd** [comment]
kdmapper works fine on my pc it only creates a thread on driverentry so theres nothing much special about running if you mean calling the entrypoint

**Comment by SSecrett** [comment]
used kdmapper too vanguard detecting now when start thats why gives 647 error ( kdmapper dt )

**Comment by SSecrett** [comment]
seems kdmapper is dt

**Comment by SSecrett** [comment]
fixed my issue by signing leaked cert
